"""updated surfboard model

Revision ID: 27a99fcb3e33
Revises: bbae6c73022d
Create Date: 2022-01-18 14:34:08.761284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a99fcb3e33'
down_revision = 'bbae6c73022d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surfboards', sa.Column('location', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surfboards', 'location')
    # ### end Alembic commands ###
