"""empty message

Revision ID: 5f908a02808b
Revises: ef812458396d
Create Date: 2022-01-21 21:00:21.020043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f908a02808b'
down_revision = 'ef812458396d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surfboards', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surfboards', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
