"""empty message

Revision ID: b1926804dc8b
Revises: b7cc2d550d8e
Create Date: 2022-01-21 22:50:43.195700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1926804dc8b'
down_revision = 'b7cc2d550d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surfboards', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surfboards', 'image')
    # ### end Alembic commands ###
