"""empty message

Revision ID: b7cc2d550d8e
Revises: 6e3a3971652a
Create Date: 2022-01-21 22:50:06.370566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cc2d550d8e'
down_revision = '6e3a3971652a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surfboards', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surfboards', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
